import Card from "@/src/components/Card/Card";
import ReviewSkeleton from "@/src/modules/Review/components/Loading/ReviewSkeleton";
import MarkdownViewer from "@/src/modules/Review/components/Markdown/MarkdownViewer";
import { Bot, Copy, Download } from "lucide-react";
import { downloadMarkdown, downloadReviewPDF } from "@/src/utils/download";
import { useRef, useState } from "react";
import Button from "@/src/components/CoreComponent/Button";
import { ReviewAIResponse } from "../../types/review.types";
import ReviewSummary from "../ReviewSummary";
import ReviewMetrics from "../ReviewMetrics";
import FindingSection from "../ReviewFindings/FindingSection";
import ReviewFindings from "../ReviewFindings/ReviewFindings";
import ReviewGoodPractices from "../ReviewGoodPractices";
import ReviewImprovements from "../ReviewImprovements";
import ReviewUpdatedCode from "../ReviewUpdatedCode/ReviewUpdatedCode";
import NextSteps from "../NextSteps";
import Assistant from "../ReviewAssistant/Assistant";

interface ReviewPanelProps {
  review: ReviewAIResponse | null;
  loading: boolean;
  error: string;
}

export default function ReviewPanel({
  review,
  loading,
  error,
}: ReviewPanelProps) {
  const [copyReview, setCopyReviw] = useState(false);
  const reviewRef = useRef<HTMLDivElement | null>(null);

  const copyReviewByAi = async () => {
    await window.navigator.clipboard.writeText("review");
    setCopyReviw(true);
    setTimeout(() => {
      setCopyReviw(false);
    }, 2000);
  };

  return (
    <div ref={reviewRef}>
      <Card className="flex h-full flex-col overflow-hidden p-0">
        {/* Header */}
        <div className="flex flex-col items-center justify-between border-b border-slate-700 px-2 py-2">
          <div>
            <h2 className="text-xl font-semibold text-white">AI Review</h2>

            <p className="mt-1 text-sm text-slate-400">
              Suggestions generated by the AI model.
            </p>
          </div>

          {!!review && !loading && (
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                size="sm"
                variant="secondary"
                className="w-auto"
                onClick={copyReviewByAi}
              >
                {copyReview ? (
                  <>
                    <Copy size={16} />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy size={16} />
                    Copy
                  </>
                )}
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                className="w-auto"
                onClick={() => {
                  downloadMarkdown("review", "review");
                }}
              >
                <Download size={16} />
                Download
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                className="w-auto"
                onClick={() => {
                  if (!reviewRef.current) return;
                  downloadReviewPDF({
                    filename: "ai-review",
                    language: "JavaScript", // Replace with actual language if available
                    code: reviewRef.current.innerText, // Replace with actual code if available
                    review: reviewRef.current.innerText,
                  });
                }}
              >
                <Download size={16} />
                PDF
              </Button>
            </div>
          )}
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto">
          {loading && <ReviewSkeleton />}
          {!loading && error && (
            <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-300">
              {error}
            </div>
          )}

          <div>
            {!loading && !error && review && (
              // <MarkdownViewer content={review} />
              <>
                <ReviewSummary
                  overallScore={review.summary.overallScore}
                  overallComment={review.summary.overallComment}
                  riskLevel={review.summary.riskLevel}
                />
                <ReviewMetrics metrics={review.metrics} />
                <ReviewFindings findings={review.findings} />
                <ReviewGoodPractices goodPractices={review.goodPractices} />
                <ReviewImprovements improvements={review.improvements} />
                <ReviewUpdatedCode
                  language="javascript"
                  updatedCode={review.updatedCode}
                />
                <NextSteps steps={review.nextSteps} />
                <Assistant
                  language={"language"}
                  code={"originalCode"}
                  review={JSON.stringify(review)}
                />
              </>
            )}
          </div>

          {!loading && !error && !review && (
            <div className="flex h-full flex-col items-center justify-center text-center text-slate-500">
              <Bot size={48} className="mb-4 text-slate-600" />
              <h3 className="text-lg font-medium text-slate-300">
                No Review Yet
              </h3>

              <p className="mt-2 max-w-xs">
                Paste your source code and click
                <span className="font-medium text-white"> Review Code</span> to
                generate an AI review.
              </p>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
