import Card from "@/src/components/Card/Card";
import ReviewSkeleton from "@/src/modules/Review/components/Loading/ReviewSkeleton";
import MarkdownViewer from "@/src/modules/Review/components/Markdown/MarkdownViewer";
import { Bot, Copy, Download } from "lucide-react";
import Button from "../../../../components/Button/Button";
import { downloadMarkdown, downloadReviewPDF } from "@/src/utils/download";
import { useRef, useState } from "react";

interface ReviewPanelProps {
  review: string;
  loading: boolean;
  error: string;
}

export default function ReviewPanel({
  review,
  loading,
  error,
}: ReviewPanelProps) {
  const [copyReview, setCopyReviw] = useState(false);
  const reviewRef = useRef<HTMLDivElement | null>(null);

  const copyReviewByAi = async () => {
    await window.navigator.clipboard.writeText(review);
    setCopyReviw(true);
    setTimeout(() => {
      setCopyReviw(false);
    }, 2000);
  };

  return (
    <div ref={reviewRef}>
      <Card className="flex h-full flex-col overflow-hidden p-0">
        {/* Header */}
        <div className="flex flex-col items-center justify-between border-b border-slate-700 px-2 py-2">
          <div>
            <h2 className="text-xl font-semibold text-white">AI Review</h2>

            <p className="mt-1 text-sm text-slate-400">
              Suggestions generated by the AI model.
            </p>
          </div>

          {!!review && !loading && (
            <div className="flex flex-wrap gap-2">
              <button
                onClick={copyReviewByAi}
                className="
              flex
              items-center
              gap-2
              rounded-lg
              border
              border-slate-700
              px-4
              py-2
              text-sm
              text-slate-300
              transition
              hover:bg-slate-800
            "
              >
                {copyReview ? (
                  <>
                    <Copy size={16} />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy size={16} />
                    Copy
                  </>
                )}
              </button>
              <button
                onClick={() => {
                  downloadMarkdown(review, "review");
                }}
                className="flex items-center gap-2 rounded-lg
              border
              border-slate-700
              px-1
              py-1
              text-sm
              text-slate-300
              transition
              hover:bg-slate-800
            "
              >
                <Download size={16} />
                Download
              </button>
              <button
                onClick={() => {
                  if (!reviewRef.current) return;

                  downloadReviewPDF({
                    filename: "ai-review",
                    language: "JavaScript", // Replace with actual language if available
                    code: reviewRef.current.innerText, // Replace with actual code if available
                    review: reviewRef.current.innerText,
                  });
                }}
                className="
      flex
      items-center
      gap-2
      rounded-lg
      border
      border-slate-700
      px-4
      py-2
      text-sm
      text-slate-300
      transition
      hover:bg-slate-800
      cursor-pointer
  "
              >
                <Download size={16} />
                PDF
              </button>
            </div>
          )}
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6">
          {loading && <ReviewSkeleton />}

          {!loading && error && (
            <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-300">
              {error}
            </div>
          )}

          <div>
            {!loading && !error && review && (
              <MarkdownViewer content={review} />
            )}
          </div>

          {!loading && !error && !review && (
            <div className="flex h-full flex-col items-center justify-center text-center text-slate-500">
              <Bot size={48} className="mb-4 text-slate-600" />

              <h3 className="text-lg font-medium text-slate-300">
                No Review Yet
              </h3>

              <p className="mt-2 max-w-xs">
                Paste your source code and click
                <span className="font-medium text-white"> Review Code</span> to
                generate an AI review.
              </p>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
