import Card from "@/src/components/Card/Card";
import ReviewSkeleton from "@/src/components/Loading/ReviewSkeleton";
import MarkdownViewer from "@/src/components/Markdown/MarkdownViewer";
import { Bot, Copy } from "lucide-react";

interface ReviewPanelProps {
  review: string;
  loading: boolean;
  error: string;
}

export default function ReviewPanel({
  review,
  loading,
  error,
}: ReviewPanelProps) {
  return (
    <Card className="flex h-full flex-col overflow-hidden p-0">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-700 px-2 py-2">
        <div>
          <h2 className="text-xl font-semibold text-white">AI Review</h2>

          <p className="mt-1 text-sm text-slate-400">
            Suggestions generated by the AI model.
          </p>
        </div>

        {!!review && !loading && (
          <button
            onClick={() => navigator.clipboard.writeText(review)}
            className="
              flex
              items-center
              gap-2
              rounded-lg
              border
              border-slate-700
              px-4
              py-2
              text-sm
              text-slate-300
              transition
              hover:bg-slate-800
            "
          >
            <Copy size={16} />
            Copy
          </button>
        )}
      </div>

      {/* Body */}
      <div className="flex-1 overflow-y-auto p-6">
        {loading && <ReviewSkeleton />}

        {!loading && error && (
          <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-300">
            {error}
          </div>
        )}

        {!loading && !error && review && <MarkdownViewer content={review} />}

        {!loading && !error && !review && (
          <div className="flex h-full flex-col items-center justify-center text-center text-slate-500">
            <Bot size={48} className="mb-4 text-slate-600" />

            <h3 className="text-lg font-medium text-slate-300">
              No Review Yet
            </h3>

            <p className="mt-2 max-w-xs">
              Paste your source code and click
              <span className="font-medium text-white"> Review Code</span> to
              generate an AI review.
            </p>
          </div>
        )}
      </div>
    </Card>
  );
}
