"use client";

import AppLayout from "@/src/layouts/AppLayout";
import Button from "@/src/components/Button/Button";
import Card from "@/src/components/Card/Card";
import CodeEditor from "@/src/components/Editor/CodeEditor";
import MarkdownViewer from "@/src/components/Markdown/MarkdownViewer";
import { useState } from "react";
import { reviewCode } from "@/src/services/review.services";
import ReviewSkeleton from "@/src/components/Loading/ReviewSkeleton";

import { Loader2 } from "lucide-react";

export default function ReviewPage() {
  const [review, setReview] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [code, setCode] = useState("");
  const [language, setLanguage] = useState("javascript");

  const handleReviewClick = async () => {
    if (!code.trim()) {
      setError("Please paste some code before reviewing.");
      return;
    }
    setLoading(true);
    setError("");

    try {
      const res = await reviewCode({
        language: language,
        code: code,
      });

      setReview(res.data.review);
    } catch {
      setError("Unable to review your code. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <AppLayout>
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Header */}
        <section>
          <h1 className="text-3xl font-bold">AI Code Review</h1>
          <p className="mt-2 text-gray-600">
            Paste your code below and let the AI provide feedback and
            suggestions.
          </p>
        </section>

        {/* Editor */}
        <Card className="p-0 overflow-hidden">
          <div className="flex items-center justify-between border-b border-slate-700 px-6 py-4">
            <div>
              <h2 className="text-lg font-semibold">Monaco Editor</h2>
            </div>

            <select
              className="
      rounded-lg
      border
      border-slate-700
      bg-slate-900
      px-4
      py-2
      text-sm
      text-white
      outline-none
    "
            >
              <option>JavaScript</option>
              <option>TypeScript</option>
              <option>Python</option>
              <option>Java</option>
            </select>
          </div>

          <CodeEditor code={code} language={language} onChange={setCode} />
          <div className="mt-3 flex justify-between text-sm text-slate-500">
            <span>{language}</span>

            <span>{code.length.toLocaleString()} characters</span>
          </div>
        </Card>
        {/* Action */}
        <div className="flex justify-end">
          <Button
            onClick={handleReviewClick}
            disabled={loading || code.trim() === ""}
            className="px-6 py-3"
          >
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Reviewing...
              </>
            ) : (
              "Review Code"
            )}
          </Button>
        </div>

        {/* AI Response */}
        <Card className="p-6">
          <div className="mb-6">
            <h2 className="text-2xl font-semibold">AI Review</h2>

            <p className="mt-1 text-sm text-slate-400">
              Suggestions generated by the AI model.
            </p>
          </div>

          <Card>
            {loading && <ReviewSkeleton />}

            {!loading && error && (
              <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-300">
                {error}
              </div>
            )}

            <div className="mb-6 flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-semibold">AI Review</h2>

                <p className="text-sm text-slate-400">
                  Suggestions generated by the AI model.
                </p>
              </div>

              {!!review && (
                <button
                  onClick={() => navigator.clipboard.writeText(review)}
                  className="rounded-lg border border-slate-700 px-4 py-2 text-sm hover:bg-slate-800"
                >
                  Copy Review
                </button>
              )}
            </div>

            {!loading && !error && <MarkdownViewer content={review} />}
          </Card>
        </Card>
      </div>
    </AppLayout>
  );
}
